### ISSUE TITLE
The Language Grammars

### ISSUE THREAD

**Issue by AdamSpeight2008** [ljw1004/vbspec#2]
@ljw1004 
I've typed out the grammar for both languages [here](https://github.com/AdamSpeight2008/Grammars)
Converting them to use the same specification for the grammar language. Very similar to BNF.

-Adam

**Comment by ljw1004** [comment]
Hi Adam! How should I understand this? How does it relate to the grammars that I typed out in ANTLR format?

**Comment by AdamSpeight2008** [comment]
@ljw1004 Please note that these are from sources I (as an external contributor) can locate..
The definition of the Grammar is [defined here](https://github.com/AdamSpeight2008/Grammars/blob/master/Grammar.txt)
The rule `Enviroment-Body ::=` requires environment support.

I see a few differences. (don't know if this is due to language change since VS2012)

ANTLR

```
QualifiedTypeName
    : Identifier TypeArguments? (Period IdentifierOrKeyword TypeArguments?)*
    | 'Global' Period IdentifierOrKeyword TypeArguments?
      (Period IdentifierOrKeyword TypeArguments?)*
    ;
```

```
QualifiedTypeName                 ::=   ( Identifier TypeArguments? )
                                      | ( "Global" Period IdentifierOrKeyword TypeArguments? )
                                      | ( QualifiedTypeName Period IdentifierOrKeyword TypeArguments? )
```

**Comment by ljw1004** [comment]
The ANTLR version also comes from the public published VB spec, dating back to VS2012, same as what you can find.

The two snippets you quoted describe the same language. I expressed it differently because the recursive definition was a bit gratuitous in this case.

Do you have a proposal for what to do with your version of the grammars? Or is this issue just an "FYI"?

**Comment by AdamSpeight2008** [comment]
Mainly FYI, 

It would good if we could match up the grammar definitions, to sections of the Roslyn VB Parser source code. Plus some tool that can verify that it matches, its specifications.
-Adam

**Comment by ljw1004** [comment]
The link I wanted was from the grammar definitions to the Roslyn SyntaxTree nodes, since that would be the commonest use-case (i.e. people who are writing analyzers and need to consume it). Unfortunately the Roslyn SyntaxTree nodes are all a huge single file that chokes web-browsers and there doesn't seem any other good place to link to. Linking to parser source code would only benefit folks who are hacking on the VB parser, which seems like a very small number.

I don't reckon it's worth investing in work to validate that the parser consumes the exact same language as described by the spec. If we find discrepancies, they'd either be compiler bugs that aren't worth fixing because folks don't run into them, or spec bugs that would be worth the effort to fix but not worth the effort to find. That's my opinion.

I was interested that ANTLR4 can now generate parsers with much more complex grammars including left-recursion. Unfortunately it doesn't handle recursive left-recursion so that won't help.

For me the most concrete practical use has been computing the "MayBeFollowedBy" sets as found in the hyperlinked form of the grammar. That allowed us to figure out how to add new parsing features to the language without introducing ambiguity.
